{"name": "test_view_failure_reason", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <TestCases.Package_entity_management.TC_failure_reason.Test_Failure_Reason testMethod=test_view_failure_reason>\n\n    @allure.description(\"Should view the created failure reason\")\n    @allure.severity(severity_level=\"CRITICAL\")\n    @pytest.mark.order(7_06)\n    def test_view_failure_reason(self):\n        self.failure_reason =failure_reason(self.driver)\n>       self.failure_reason.view_failure_reason(\"Adaptor issue 5\")\n\nTestCases/Package_entity_management/TC_failure_reason.py:67: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page_objects.entity_Management.failure_reason.failure_reason object at 0x7fae417df490>, name = 'Adaptor issue 5'\n\n    def view_failure_reason(self,name):\n        element = WebDriverWait(self.driver, 10).until(EC.presence_of_all_elements_located((By.XPATH,self.created_failure_reason_in_listView_xpath)))\n        for x in element:\n            if x.text in name:\n                x.click()\n                if WebDriverWait(self.driver, 50).until(\n                    EC.title_contains('Brighter App | Failure Reason | View')):\n                        assert True\n                else:\n                    allure.attach(self.driver.get_screenshot_as_png(),name=\"view_failure_reason\",attachment_type=AttachmentType.PNG)\n                    # self.driver.save_screenshot(\"view_failure_reason.png\")\n                    assert False\n                break\n            else:\n                allure.attach(self.driver.get_screenshot_as_png(),name=\"listView_failure_reason_notFound\",attachment_type=AttachmentType.PNG)\n                # self.driver.save_screenshot(\"listView_failure_reason_notFound.png\")\n>               assert False\nE               AssertionError\n\npage_objects/entity_Management/failure_reason.py:105: AssertionError"}, "description": "Should view the created failure reason", "attachments": [{"name": "listView_failure_reason_notFound", "source": "e3905dbb-64e6-42d4-9d64-6fdfbf9941f8-attachment.png", "type": "image/png"}], "start": 1678879363276, "stop": 1678879363489, "uuid": "977a7b85-adbe-4005-a7d1-8eef9e7dea7e", "historyId": "419ce3912a4f4ee647fd215e6d323f07", "testCaseId": "6315c7fd8ab89c6174f7791ca4ccfc3f", "fullName": "Test_Suites.test_all_module.Test_Failure_Reason#test_view_failure_reason", "labels": [{"name": "severity", "value": "CRITICAL"}, {"name": "tag", "value": "order(706)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Test_Suites"}, {"name": "suite", "value": "test_all_module"}, {"name": "subSuite", "value": "Test_Failure_Reason"}, {"name": "host", "value": "sujith-HP-Compaq-Elite-8300-SFF"}, {"name": "thread", "value": "63930-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Suites.test_all_module"}]}