{"name": "test_edit_failure_reason", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <TestCases.Package_entity_management.TC_failure_reason.Test_Failure_Reason testMethod=test_edit_failure_reason>\n\n    @allure.description(\"Should able to edit and save the failure reason and navigate to failure reason page\")\n    @allure.severity(severity_level=\"CRITICAL\")\n    @pytest.mark.order(7_09)\n    def test_edit_failure_reason(self):\n        self.failure_reason =failure_reason(self.driver)\n        self.failure_reason.edit_name(\"Adaptor issue 51\")\n>       self.failure_reason.save_information_button()\n\nTestCases/Package_entity_management/TC_failure_reason.py:88: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page_objects.entity_Management.failure_reason.failure_reason object at 0x7f8bd459f670>\n\n    def save_information_button(self):\n        self.driver.find_element(By.ID,self.save_information_button_id).click()\n        self.msg=WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.XPATH,'//div[@class=\"toastr-text\"]//p[normalize-space()=\"Successfully Updated\"]')))\n        if \"Successfully Updated\" in self.msg.text:\n            assert True\n        else:\n            allure.attach(self.driver.get_screenshot_as_png(),name=\"edit_asset_category_toast\",attachment_type=AttachmentType.PNG)\n            # self.driver.save_screenshot(\"edit_asset_category_toast.png\")\n>           assert False\nE           AssertionError\n\npage_objects/entity_Management/failure_reason.py:160: AssertionError"}, "description": "Should able to edit and save the failure reason and navigate to failure reason page", "attachments": [{"name": "edit_asset_category_toast", "source": "2d080f4a-5a75-4e2a-9ef8-1d4503c3cbae-attachment.png", "type": "image/png"}], "start": 1678878577676, "stop": 1678878578778, "uuid": "cc43268b-9c11-462f-8042-832ddb4ba54b", "historyId": "a7285176658aa9e162beaf097749e320", "testCaseId": "b4475fcc55fd6edb89a560b8fab620b4", "fullName": "Test_Suites.test_all_module.Test_Failure_Reason#test_edit_failure_reason", "labels": [{"name": "severity", "value": "CRITICAL"}, {"name": "tag", "value": "order(709)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Test_Suites"}, {"name": "suite", "value": "test_all_module"}, {"name": "subSuite", "value": "Test_Failure_Reason"}, {"name": "host", "value": "sujith-HP-Compaq-Elite-8300-SFF"}, {"name": "thread", "value": "60441-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Suites.test_all_module"}]}