{"uuid": "af339501-dbf3-4678-8489-268b27772de4", "children": ["2a0070e1-e3a9-4a25-a103-ed63a9edbf2f", "f598d23e-30c2-4cb7-abd7-19f876d99930", "1712e986-d607-4d72-a9fb-3ebf07cf0b5d", "740af86e-6f17-4c96-8321-d8d7be3ed074", "53283634-1b64-4182-b4b4-6518a0410028", "ae6e5647-b794-4254-9977-22e4592ba6f6", "08a63bdf-768a-4ea5-add3-5b2c097f4848", "4e5e11b7-e5ea-49ae-b207-5c2a236e89a4", "08fd521d-5594-4bba-8cd5-e77309b5dbb3", "372f4171-ff5b-422e-89b6-0fa3739b6ba5", "aa7160aa-da42-49ca-8feb-3a4481270dfd", "d7419fd7-8a7c-4c44-8c9c-635a3ab4808b", "ab0a90c2-e1a9-4a78-8583-b642894ef07c", "8ed08558-3d01-4aec-8734-8fa1d418ad9e", "7b85440b-6e5f-4c8e-a93b-3994ef134818", "1d37736c-a385-48ad-80ef-0789c9da7334", "888b2a4a-d22d-4451-a5d4-38b9c29b5075", "d283e94c-1cb3-4005-82f3-4511654cf592", "3f7005fc-5e24-4eec-ac0a-340499b72632", "181dc0b5-15b1-4850-aecc-4df3f752237e", "2ef4784f-95e4-4094-a976-8dcfeb15ee87", "5d5ebac3-babf-480d-be63-5ad9c0a1be25", "fee9a76b-c25e-43dc-8701-b5448e1eec35", "fdaf5195-be29-435e-b2dc-1c56b43bcc7a", "5cddb006-6bc9-46f2-a351-6be8c7d94749", "60c73169-ddaa-48dd-9493-4c83387196c0", "13ddd20d-9500-406a-a766-799b020484db", "25bae329-3979-4ba4-ab29-c2307066196f", "24159ca4-6191-474c-804a-ab869e81890f", "61c30314-0284-494e-9e1f-a6680f7ade59", "26a68e1b-6acf-44a1-92c7-4f77b49a7e61", "54b2962a-6870-48a0-b40a-85036971038b", "155abb34-9090-4348-8cb0-c29acfb8aa55", "b5856fce-8e7d-4ba2-894c-16dd70bc3e28", "e8935f4d-76d4-48cb-91c3-4bec0d71a486", "34ef092c-ce40-40a2-a97f-a9b0067064bd"], "befores": [{"name": "init_driver", "status": "passed", "start": 1678866170808, "stop": 1678866173730}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=42103): Max retries exceeded with url: /session/cb04006bf00398aa0dbc16923cf6c29f/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0944193b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/sujith/codebase/BGE_Framework_Design/Test_Suites/conftest.py\", line 29, in init_driver\n    driver.delete_all_cookies()\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 730, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678866300892, "stop": 1678866300895}], "start": 1678866170808, "stop": 1678866300895}