{"name": "test_create_failure_reason", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <TestCases.Package_entity_management.TC_failure_reason.Test_Failure_Reason testMethod=test_create_failure_reason>\n\n    @allure.description(\"Should able to create failure reason\")\n    @allure.severity(severity_level=\"CRITICAL\")\n    @pytest.mark.order(7_04)\n    def test_create_failure_reason(self):\n        self.failure_reason =failure_reason(self.driver)\n        self.failure_reason.name(\"Adaptor issue 5\")\n>       self.failure_reason.create_failure_reason()\n\nTestCases/Package_entity_management/TC_failure_reason.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page_objects.entity_Management.failure_reason.failure_reason object at 0x7f8bd45b0c40>\n\n    def create_failure_reason(self):\n        self.driver.find_element(By.XPATH,self.add_failure_reason_xpath).click()\n        self.msg=WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.XPATH,'//div[@class=\"toastr-text\"]//p[normalize-space()=\"Successfully Created\"]')))\n        if \"Successfully Created\" in self.msg.text:\n            assert True\n        else:\n            allure.attach(self.driver.get_screenshot_as_png(),name=\"create_failure_reason_toast\",attachment_type=AttachmentType.PNG)\n            # self.driver.save_screenshot(\"create_failure_reason_toast.png\")\n>           assert False\nE           AssertionError\n\npage_objects/entity_Management/failure_reason.py:75: AssertionError"}, "description": "Should able to create failure reason", "attachments": [{"name": "create_failure_reason_toast", "source": "85d3ac2b-fb73-407d-8c7e-5a7719a553de-attachment.png", "type": "image/png"}], "start": 1678878561483, "stop": 1678878562493, "uuid": "af9ac51b-89f0-4d50-901d-a4a6b9812f84", "historyId": "60ea155cbc409e52f1d6514719c0e268", "testCaseId": "52546f71e61a22bbd443f829bfcacd4d", "fullName": "Test_Suites.test_all_module.Test_Failure_Reason#test_create_failure_reason", "labels": [{"name": "severity", "value": "CRITICAL"}, {"name": "tag", "value": "order(704)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Test_Suites"}, {"name": "suite", "value": "test_all_module"}, {"name": "subSuite", "value": "Test_Failure_Reason"}, {"name": "host", "value": "sujith-HP-Compaq-Elite-8300-SFF"}, {"name": "thread", "value": "60441-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Suites.test_all_module"}]}