{"uuid": "baea9bb3-537c-4925-a346-6ecf051fb9af", "children": ["2479473f-36d7-48bb-9376-174bcbcc6801", "47b65436-9758-46ec-b41f-046d8ab1cd49", "5fcec95c-4ff1-4489-8bf8-9dc11a49de29", "9cdd6324-f614-4149-9c8e-fc7c5933fdba", "5b5e225a-ca8d-4ada-9ae6-119428ee1c4d", "954b715d-15eb-4713-83f1-50c4fca66b15", "48171866-e8b4-4907-994f-24cd0dff26d4", "25c1d91a-cf7d-4c2d-9648-765aaa3984d3", "9ca4800e-fd1f-4d29-9ac1-02c67ed179c9", "ea443f05-d31e-4cc1-a0a3-b97bf5439abd", "bd5be43f-7bac-4877-ab25-d143bdfa5a26", "0bb09bd7-f483-48dd-83af-7f3a5f624e2f", "131f1571-edfd-497e-be9b-ae8f54b95ed3", "aafbcfcb-bdda-4edf-aee9-8885519b1bea", "f45371d3-2446-4904-abf3-b3d631a2d961", "49028576-d306-4aa2-a40f-38324cf31692", "2eddcbbb-7152-4a54-afb8-c04d103aea43", "ae0db22c-6ebb-4e2e-9a3f-d310a790ad3c", "1afc0f6f-1253-4841-b7a7-81cc7a7075a5", "73328100-dd7f-47dc-888c-679257450d47", "783de253-c4e8-4300-8055-2b18e4465128", "89e32d8c-3fa1-4726-bcf7-c712f8d1f0d5", "c6288bcd-108a-4692-97c7-89bf5427b4fe", "36139336-3b7a-4771-9de0-41625e058a6b", "c831c316-f0f9-4372-a23a-43acd5b7094c", "89faa810-6033-4789-bbec-8db5a7571248", "114d7a13-8e1b-40e7-aaeb-6d08c4035125", "4100c637-33f8-4e65-8a68-c59ab521d122", "589cb50a-8c0c-40a3-b082-0840fce15bb1", "62e7b65f-6d07-428e-a134-00bfb272da88", "7c1cded0-97f1-4f94-ac53-2380056cbeea", "ff590457-a1ab-4584-82b5-bf213b120edb", "524c89fd-9c5b-48e7-b465-8433073c1bd1", "b655c9f2-9652-4653-816a-482e2f09edd0", "977a7b85-adbe-4005-a7d1-8eef9e7dea7e", "b9c076f0-b2b3-493f-9144-1a8f531a0937"], "befores": [{"name": "init_driver", "status": "passed", "start": 1678879271610, "stop": 1678879272786}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52645): Max retries exceeded with url: /session/1483db73cc03b149baacd3536269f539/cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae416c0670>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/home/sujith/codebase/BGE_Framework_Design/Test_Suites/conftest.py\", line 29, in init_driver\n    driver.delete_all_cookies()\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 730, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/sujith/.local/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678879364618, "stop": 1678879364621}], "start": 1678879271610, "stop": 1678879364621}